libs.versions.toml

Bumped kmehr module to 1.0.65-gb803f45d75 and kraken-common

Bumped kmehr module to 1.0.65-gb803f45d75 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.67-ga506093a9f and kraken-common

Bumped kmehr module to 1.0.67-ga506093a9f and kraken-common

---

libs.versions.toml
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/MessageServiceImpl.kt

Bumped kmehr module to 1.0.68-gcf62222746 and kraken-common

Bumped kmehr module to 1.0.68-gcf62222746 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.70-g8fb799b203 and kraken-common

Bumped kmehr module to 1.0.70-g8fb799b203 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.72-gbaa3cb2626 and kraken-common

Bumped kmehr module to 1.0.72-gbaa3cb2626 and kraken-common

---

libs.versions.toml
lite-core/build.gradle.kts
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/AccessLogServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/AgendaServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/CalendarItemServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/ClassificationServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/CodeServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/ContactServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/DeviceServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/DocumentServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/FormServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/HealthElementServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/HealthcarePartyServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/InvoiceServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/MaintenanceTaskServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/MedicalLocationServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/MessageServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/PatientServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/TimeTableServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/UserServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/config/LiteLogicConfig.kt

Bumped kmehr module to 1.0.75-g9e5765c16d and kraken-common

Bumped kmehr module to 1.0.75-g9e5765c16d and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.76-gba4ae608d2 and kraken-common

Bumped kmehr module to 1.0.76-gba4ae608d2 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.78-g69e8ad5d19 and kraken-common

Bumped kmehr module to 1.0.78-g69e8ad5d19 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.79-g36ba258ffa and kraken-common

Bumped kmehr module to 1.0.79-g36ba258ffa and kraken-common

---

.github/workflows/license-report.yaml
libs.versions.toml

Bumped kmehr module to 1.0.84-g97d4441b0a and kraken-common

Bumped kmehr module to 1.0.84-g97d4441b0a and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.86-g4b53c4d652 and kraken-common

Bumped kmehr module to 1.0.86-g4b53c4d652 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.87-g4e1d144043 and kraken-common

Bumped kmehr module to 1.0.87-g4e1d144043 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.88-g5b03bb038f and kraken-common

Bumped kmehr module to 1.0.88-g5b03bb038f and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.89-g6925c2eaff and kraken-common

Bumped kmehr module to 1.0.89-g6925c2eaff and kraken-common

---

libs.versions.toml
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/RecoveryDataServiceImpl.kt

Bumped kmehr module to 1.0.90-g1d0abd9321 and kraken-common

Add waitForRecoveryData method

---

libs.versions.toml
lite-core/build.gradle.kts
lite-core/src/main/kotlin/org/taktik/icure/config/LiteWebConfig.kt
lite-core/src/main/kotlin/org/taktik/icure/services/external/http/WebSocketOperationHandler.kt

Bumped kmehr module to 1.0.94-g4e3c6361f6 and kraken-common

Bumped kmehr module to 1.0.94-g4e3c6361f6 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.95-gd2b7556d48 and kraken-common

Bumped kmehr module to 1.0.95-gd2b7556d48 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.98-g9f1378b09a and kraken-common

Bumped kmehr module to 1.0.98-g9f1378b09a and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.100-gd0d401a3c5 and kraken-common

Bumped kmehr module to 1.0.100-gd0d401a3c5 and kraken-common

---

libs.versions.toml
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/DataOwnerServiceImpl.kt

Bumped kmehr module to 1.0.102-g817ceaef6d and kraken-common

Bumped kmehr module to 1.0.102-g817ceaef6d and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.103-g0e9f7d7eb2 and kraken-common

Bumped kmehr module to 1.0.103-g0e9f7d7eb2 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.107-gf93e1e66ff and kraken-common

Bumped kmehr module to 1.0.107-gf93e1e66ff and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.108-ge880531ffd and kraken-common

Bumped kmehr module to 1.0.108-ge880531ffd and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.111-g7563879ea4 and kraken-common

Bumped kmehr module to 1.0.111-g7563879ea4 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.112-g4c46df2532 and kraken-common

Bumped kmehr module to 1.0.112-g4c46df2532 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.117-gb6f02780a3 and kraken-common

Bumped kmehr module to 1.0.117-gb6f02780a3 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.125-g0ffad24b2a and kraken-common

Bumped kmehr module to 1.0.125-g0ffad24b2a and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.126-g0e21e849a6 and kraken-common

Bumped kmehr module to 1.0.126-g0e21e849a6 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.127-g4429a96be6 and kraken-common

Bumped kmehr module to 1.0.127-g4429a96be6 and kraken-common

---

libs.versions.toml
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/AccessLogServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/AgendaServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/ArticleServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/CalendarItemServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/CalendarItemTypeServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/ClassificationServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/ClassificationTemplateServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/ContactServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/DeviceServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/DocumentServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/DocumentTemplateServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/EntityTemplateServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/FormServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/FormTemplateServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/FrontEndMigrationServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/HealthElementServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/HealthcarePartyServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/InsuranceServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/InvoiceServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/KeywordServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/MaintenanceTaskServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/MedicalLocationServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/MessageServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/PatientServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/PlaceServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/ReceiptServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/TimeTableServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/UserServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/config/LiteLogicConfig.kt

Bumped kmehr module to 1.0.1445-g1f48bd55c0 and kraken-common

Bumped kmehr module to 1.0.1445-g1f48bd55c0 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.1446-gf450c1ddc5 and kraken-common

Bumped kmehr module to 1.0.1446-gf450c1ddc5 and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.1448-g7506d9f90e and kraken-common

Bumped kmehr module to 1.0.1448-g7506d9f90e and kraken-common

---

libs.versions.toml

Bumped kmehr module to 1.0.14410-g00e6677291 and kraken-common

Bumped kmehr module to 1.0.14410-g00e6677291 and kraken-common

---

lite-core/src/main/kotlin/org/taktik/icure/config/LiteSecurityConfig.kt
lite-core/src/main/kotlin/org/taktik/icure/errors/GlobalErrorHandler.kt
lite-core/src/main/kotlin/org/taktik/icure/properties/SecurityProperties.kt
lite-core/src/main/kotlin/org/taktik/icure/security/CloudJwtValidator.kt
lite-core/src/main/kotlin/org/taktik/icure/security/LiteAuthProperties.kt
lite-core/src/main/kotlin/org/taktik/icure/security/LiteAuthenticationManager.kt
lite-core/src/main/kotlin/org/taktik/icure/services/external/rest/lite/v2/controllers/support/LoginController.kt

Add for login to kraken-lite instance using a cloud instance jwt

Lite login by cloud jwt

---

libs.versions.toml

Bumped kmehr module to 1.0.14432-g2948cb194e and kraken-common

Bumped kmehr module to 1.0.14432-g2948cb194e and kraken-common

---

libs.versions.toml

Bumped kmehr module to 25.6.0-g2948cb194e and kraken-common

Bumped kmehr module to 25.6.0-g2948cb194e and kraken-common

---

libs.versions.toml

Bumped kmehr module to 25.7.2-g1f972accd9 and kraken-common

Bumped kmehr module to 25.7.2-g1f972accd9 and kraken-common

---

libs.versions.toml
lite-core/src/main/kotlin/org/taktik/icure/asyncservice/impl/ApplicationSettingsServiceImpl.kt
lite-core/src/main/kotlin/org/taktik/icure/config/LiteLogicConfig.kt

Bumped kmehr module to 25.9.0-g60d77f9cab and kraken-common

Bumped kmehr module to 25.9.0-g60d77f9cab and kraken-common
